openapi: 3.0.3
info:
  title: MelkinoProject
  version: 1.0.0
  description: Your project description
paths:
  /library/authors/:
    get:
      operationId: library_authors_list
      parameters:
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      tags:
      - library
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
          description: ''
    post:
      operationId: library_authors_create
      tags:
      - library
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Author'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Author'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
          description: ''
  /library/authors/{id}/:
    get:
      operationId: library_authors_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - library
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
          description: ''
    put:
      operationId: library_authors_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - library
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Author'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Author'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
          description: ''
    patch:
      operationId: library_authors_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - library
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedAuthor'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedAuthor'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedAuthor'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
          description: ''
    delete:
      operationId: library_authors_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - library
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /library/books/:
    get:
      operationId: library_books_list
      parameters:
      - in: query
        name: availability_status
        schema:
          type: boolean
      - in: query
        name: publication_date
        schema:
          type: string
          format: date
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      tags:
      - library
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
          description: ''
    post:
      operationId: library_books_create
      tags:
      - library
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Book'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Book'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
          description: ''
  /library/books/{id}/:
    get:
      operationId: library_books_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - library
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
          description: ''
    put:
      operationId: library_books_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - library
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Book'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Book'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
          description: ''
    patch:
      operationId: library_books_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - library
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedBook'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedBook'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedBook'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
          description: ''
    delete:
      operationId: library_books_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - library
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /user/register/:
    post:
      operationId: user_register_create
      tags:
      - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
components:
  schemas:
    Author:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          nullable: true
          maxLength: 100
        birth_date:
          type: string
          format: date
          nullable: true
        bio:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
          nullable: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
          nullable: true
        user:
          type: integer
      required:
      - created_at
      - id
      - updated_at
      - user
    Book:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        authors:
          type: array
          items:
            $ref: '#/components/schemas/Author'
        title:
          type: string
          nullable: true
          maxLength: 200
        genre:
          type: string
          nullable: true
          maxLength: 100
        publication_date:
          type: string
          format: date
          nullable: true
        availability_status:
          type: boolean
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
          nullable: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
          nullable: true
        user:
          type: integer
          nullable: true
      required:
      - authors
      - created_at
      - id
      - updated_at
    PatchedAuthor:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          nullable: true
          maxLength: 100
        birth_date:
          type: string
          format: date
          nullable: true
        bio:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
          nullable: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
          nullable: true
        user:
          type: integer
    PatchedBook:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        authors:
          type: array
          items:
            $ref: '#/components/schemas/Author'
        title:
          type: string
          nullable: true
          maxLength: 200
        genre:
          type: string
          nullable: true
          maxLength: 100
        publication_date:
          type: string
          format: date
          nullable: true
        availability_status:
          type: boolean
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
          nullable: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
          nullable: true
        user:
          type: integer
          nullable: true
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        password:
          type: string
          title: گذرواژه
          maxLength: 128
        last_login:
          type: string
          format: date-time
          nullable: true
          title: آخرین ورود
        is_superuser:
          type: boolean
          title: ابرکاربر
          description: نشان می‌دهد که این کاربر همهٔ اجازه‌ها را دارد بدون آنکه به
            صراحت به او اختصاص داده شده باشد.
        username:
          type: string
          title: نام کاربری
          description: الزامی. 150 کاراکتر یا کمتر. فقط شامل حروف، اعداد، و علامات
            @/./+/-/_
          pattern: ^[\w.@+-]+$
          maxLength: 150
        first_name:
          type: string
          title: نام
          maxLength: 150
        last_name:
          type: string
          title: نام خانوادگی
          maxLength: 150
        email:
          type: string
          format: email
          title: آدرس ایمیل
          maxLength: 254
        is_staff:
          type: boolean
          title: وضعیت کارمندی
          description: نشان می‌دهد که آیا این کاربر می‌تواند وارد این وبگاه مدیریت
            شود یا خیر.
        is_active:
          type: boolean
          title: فعال
          description: نشان می‌دهد که آیا این کاربر اجازهٔ فعالیت دارد یا خیر. به
            جای حذف کاربر این تیک را بردارید.
        date_joined:
          type: string
          format: date-time
          title: تاریخ پیوستن
        fullname:
          type: string
          nullable: true
          maxLength: 80
        bio:
          type: string
          nullable: true
          maxLength: 80
      required:
      - id
      - password
      - username
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
